name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel

    steps:
      - name: Install dependencies
        run: pacman -Syu --noconfirm git python cmake ninja sdl3 sdl3_image sdl3_ttf fmt spdlog cereal doxygen unzip tar xz

      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Build docs
        run: doxygen Doxyfile

      - name: Setup emsdk
        uses: emscripten-core/setup-emsdk@v15
        with:
          version: 5.0.2
          emsdk-version: 5.0.5
          actions-cache-folder: 'emsdk-cache'


      - name: Build examples
        run: bash build-examples.sh --web-only

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          version: latest

      - name: Install dependencies
        working-directory: website
        run: pnpm install

      - name: Run pre-build script
        working-directory: website
        run: node build.js

      - name: Build website
        working-directory: website
        run: pnpm build

      - name: Upload Web Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: calamity-engine-web-build
          path: website/.output/public/

      - name: Deploy main site
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy --config wrangler-website.toml

      - name: Deploy docs
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy --config wrangler-docs.toml